// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      'apps/mobile/.expo/**',
      // Generated by `expo prebuild` from app.json, and gitignored. Build
      // output, not source.
      'apps/mobile/ios/**',
      'apps/mobile/android/**',
      'apps/desktop/out/**',
      // Edge Functions run on Deno and are linted/formatted by Deno's own
      // tooling (supabase/functions/deno.json), not the Node ESLint config.
      'supabase/functions/**',
      // Scratch output written by `supabase start` (bundled edge-runtime entry
      // point, generated secrets). Gitignored, and not ours to lint.
      'supabase/.temp/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': 'error',
    },
  },
  // Metro and Babel `require()` their config files directly, before any ESM
  // loader exists, so these must stay CommonJS even though the workspace is
  // `"type": "module"`. Rewriting them as ESM would break the toolchain, so the
  // module rules are relaxed here rather than the files being changed.
  {
    files: ['apps/mobile/*.config.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        __dirname: 'readonly',
        module: 'writable',
        require: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  prettier,
);
