// acceptInvitation Edge Function (Requirements 3.2, 3.3, 3.4, 3.5, 3.6, 3.8).
//
// An authenticated account accepts a pairing invitation by its `code`. The
// acceptance:
//   * rejects an unknown invitation (INVITATION_NOT_FOUND),
//   * rejects one accepted after its 72h window (INVITATION_EXPIRED, Req 3.5),
//   * rejects a single-use invitation that was already consumed
//     (INVITATION_ALREADY_CONSUMED, Req 3.8),
//   * rejects acceptance when either the inviter or the invitee is already in a
//     pairing (ALREADY_PAIRED, Req 3.3, 3.4, 3.6), and
//   * otherwise creates the pairing and consumes the invitation (Req 3.2, 3.8).
//
// Two layers cooperate:
//   1. PURE pre-validation with the shared `@ldr/core` `acceptInvitation`, which
//      decides the outcome from the loaded state and yields friendly, stable
//      error codes without touching the database.
//   2. An ATOMIC Postgres transaction (`public.accept_invitation` RPC) performs
//      the authoritative mutation. It re-checks every condition inside the
//      transaction and relies on the partial UNIQUE active-membership indexes so
//      that two partners accepting concurrently can never both succeed (Req 3.6)
//      and the invitation is consumed exactly once (Req 3.8).

import "jsr:@supabase/functions-js/edge-runtime.d.ts";

import { acceptInvitation } from "@ldr/core/pairing-logic";
import { handleCors } from "../_shared/cors.ts";
import {
  errorResponse,
  jsonResponse,
  statusForErrorCode,
} from "../_shared/http.ts";
import {
  authenticatedAccountId,
  serviceClient,
} from "../_shared/supabase.ts";

Deno.serve(async (req: Request) => {
  const preflight = handleCors(req);
  if (preflight) return preflight;

  if (req.method !== "POST") {
    return errorResponse(
      "METHOD_NOT_ALLOWED",
      "acceptInvitation must be called with POST.",
      405,
    );
  }

  const inviteeId = await authenticatedAccountId(req);
  if (!inviteeId) {
    return errorResponse(
      "UNAUTHENTICATED",
      "A valid authenticated session is required to accept an invitation.",
      401,
    );
  }

  let code: unknown;
  try {
    const body = await req.json();
    code = body?.code;
  } catch {
    code = undefined;
  }
  if (typeof code !== "string" || code.length === 0) {
    return errorResponse(
      "MISSING_REQUIRED_FIELD",
      "An invitation `code` is required.",
      400,
      { fields: ["code"] },
    );
  }

  const db = serviceClient();

  // Load the invitation (service role bypasses RLS).
  const { data: inv, error: invErr } = await db
    .from("invitations")
    .select("code, inviter_account_id, created_at, expires_at, status")
    .eq("code", code)
    .maybeSingle();

  if (invErr) {
    return errorResponse(
      "INTERNAL_ERROR",
      "Failed to load the invitation.",
      500,
    );
  }
  if (!inv) {
    return errorResponse(
      "INVITATION_NOT_FOUND",
      "No invitation exists for the supplied code.",
      statusForErrorCode("INVITATION_NOT_FOUND"),
    );
  }

  // Load both accounts to evaluate exclusivity (Req 3.3, 3.4).
  const { data: accounts, error: accErr } = await db
    .from("accounts")
    .select("id, pairing_id, created_at")
    .in("id", [inv.inviter_account_id, inviteeId]);

  if (accErr) {
    return errorResponse(
      "INTERNAL_ERROR",
      "Failed to load the accounts.",
      500,
    );
  }

  const inviterRow = accounts?.find((a) => a.id === inv.inviter_account_id);
  const inviteeRow = accounts?.find((a) => a.id === inviteeId);
  if (!inviterRow || !inviteeRow) {
    return errorResponse(
      "INVITATION_NOT_FOUND",
      "The invitation refers to an account that no longer exists.",
      statusForErrorCode("INVITATION_NOT_FOUND"),
    );
  }

  const now = Date.now();

  // Pure decision (reuses the shared domain logic). The pairingId here is a
  // placeholder — the authoritative id is generated by the RPC below.
  const decision = acceptInvitation({
    invitation: {
      code: inv.code,
      inviterAccountId: inv.inviter_account_id,
      createdAt: Date.parse(inv.created_at) || 0,
      expiresAt: Date.parse(inv.expires_at) || 0,
      status: inv.status,
    },
    inviter: {
      id: inviterRow.id,
      email: "",
      pairingId: inviterRow.pairing_id ?? null,
      createdAt: Date.parse(inviterRow.created_at) || now,
    },
    invitee: {
      id: inviteeRow.id,
      email: "",
      pairingId: inviteeRow.pairing_id ?? null,
      createdAt: Date.parse(inviteeRow.created_at) || now,
    },
    pairingId: "pending",
    now,
  } as unknown as Parameters<typeof acceptInvitation>[0]);

  if (!decision.ok) {
    return errorResponse(
      decision.error.code,
      decision.error.message,
      statusForErrorCode(decision.error.code),
    );
  }

  // Authoritative, atomic mutation. The RPC repeats the guards inside one
  // transaction and relies on the partial UNIQUE index to serialize concurrent
  // accepts (Req 3.6) and consume the invitation exactly once (Req 3.8).
  const { data: rpcRows, error: rpcErr } = await db.rpc("accept_invitation", {
    p_code: code,
    p_invitee: inviteeId,
    p_now: new Date(now).toISOString(),
  });

  if (rpcErr) {
    return errorResponse(
      "INTERNAL_ERROR",
      "Failed to complete the pairing transaction.",
      500,
    );
  }

  const outcome = Array.isArray(rpcRows) ? rpcRows[0] : rpcRows;
  const resultCode: string = outcome?.result_code ?? "INTERNAL_ERROR";

  if (resultCode !== "OK") {
    // A concurrent accept (or a race that changed state between the pure
    // pre-check and the transaction) is reported with the same stable codes.
    const status =
      resultCode === "INTERNAL_ERROR"
        ? 500
        : statusForErrorCode(resultCode);
    return errorResponse(
      resultCode,
      "The invitation could not be accepted.",
      status,
    );
  }

  return jsonResponse(
    {
      pairing: {
        id: outcome.pairing_id,
        memberA: inv.inviter_account_id,
        memberB: inviteeId,
        status: "active",
        createdAt: new Date(now).toISOString(),
      },
    },
    201,
  );
});
