import { describe, expect, it } from 'vitest';
import * as fc from 'fast-check';

import { ERROR_CODES } from '../errors.js';
import { isErr, isOk } from '../result.js';
import { accountId } from './common.js';
import type { AccountId } from './common.js';
import type { GameState, Move } from './game.js';
import { applyMove } from './rt-engine.js';
import {
  TIC_TAC_TOE,
  ticTacToeRuleset,
  type TicTacToeMove,
  type TicTacToeState,
} from './rt-tic-tac-toe.js';

/**
 * Property 20 (task 5.2) — Real-time move engine correctness.
 *
 * Exercises the pure {@link applyMove} engine against its concrete Tic-Tac-Toe
 * ruleset. For any reachable game state and any attempted move:
 *
 * - a **valid** move (in-progress game, the move belongs to the current-turn
 *   participant, and it claims an in-range empty cell) returns `Ok` with an
 *   *updated* state that only differs from the input in the ways the rules
 *   allow, and the caller's input state is left byte-for-byte unchanged (Req 6.4);
 * - an **invalid** move (wrong phase, non-participant/out-of-turn actor, or a
 *   rule violation) is rejected with `Err(INVALID_MOVE)` and the input state is
 *   returned unchanged (Req 6.11);
 * - the engine is **deterministic** — applying the same move to the same state
 *   twice yields identical next states, which is what makes both present
 *   partners converge on the same authoritative state.
 *
 * Everything here is pure: states are generated by folding valid moves from the
 * ruleset's initial state, and no clock or mutation is involved.
 */

// Feature: ldr-companion-app, Property 20: Real-time move engine correctness
// Validates: Requirements 6.4, 6.11

const PLAYERS: readonly [AccountId, AccountId] = [accountId('alice'), accountId('bob')];
const STRANGER = accountId('carol');

/** Snapshot for structural-equality comparison (deep clone of plain data). */
const clone = (state: TicTacToeState): TicTacToeState =>
  structuredClone(state) as TicTacToeState;

/**
 * Build a *reachable* Tic-Tac-Toe state by folding a sequence of proposed cell
 * indices through the ruleset, applying each valid move and skipping invalid or
 * post-terminal ones. This yields in-progress and terminal states alike.
 */
function reachableState(firstIndex: 0 | 1, cells: readonly number[]): TicTacToeState {
  let state = ticTacToeRuleset.createInitialState(PLAYERS, PLAYERS[firstIndex]);
  for (const cell of cells) {
    if (state.status !== 'in_progress') break;
    const move: TicTacToeMove = { type: 'place', cell };
    const result = ticTacToeRuleset.applyMove(state, state.currentTurn, move);
    if (isOk(result)) state = result.value;
  }
  return state;
}

// A reachable game state: alternating valid placements from a random first mover.
const stateArb: fc.Arbitrary<TicTacToeState> = fc
  .record({
    firstIndex: fc.constantFrom<0 | 1>(0, 1),
    cells: fc.array(fc.integer({ min: 0, max: 8 }), { minLength: 0, maxLength: 12 }),
  })
  .map(({ firstIndex, cells }) => reachableState(firstIndex, cells));

// An actor to attempt the move with: usually a participant, sometimes a stranger.
const actorArb: fc.Arbitrary<AccountId> = fc.constantFrom(PLAYERS[0], PLAYERS[1], STRANGER);

// An attempted move: mostly in-range placements, sometimes out of range.
const moveArb: fc.Arbitrary<TicTacToeMove> = fc
  .integer({ min: -2, max: 11 })
  .map((cell) => ({ type: 'place', cell }));

/** The independent oracle for whether `(actor, move)` is legal in `state`. */
function isLegal(state: TicTacToeState, actor: AccountId, move: TicTacToeMove): boolean {
  if (state.status !== 'in_progress') return false;
  if (actor !== state.players[0] && actor !== state.players[1]) return false;
  if (actor !== state.currentTurn) return false;
  const { cell } = move;
  if (!Number.isInteger(cell) || cell < 0 || cell > 8) return false;
  return state.board[cell] === null;
}

describe('rt-engine: real-time move engine correctness (property)', () => {
  it('accepts valid moves with an updated state and rejects invalid ones unchanged', () => {
    fc.assert(
      fc.property(stateArb, actorArb, moveArb, (state, actor, move) => {
        const before = clone(state);
        const result = applyMove(state as unknown as GameState, actor, move as unknown as Move);

        // The engine never mutates the caller's input state (Req 6.4, 6.11).
        expect(state).toStrictEqual(before);

        if (isLegal(state, actor, move)) {
          // Valid move → Ok with an updated, distinct state object (Req 6.4).
          expect(isOk(result)).toBe(true);
          if (!isOk(result)) return;
          const next = result.value as unknown as TicTacToeState;

          expect(next).not.toBe(state);
          // The claimed cell now belongs to the actor.
          expect(next.board[move.cell]).toBe(actor);
          // Exactly one cell changed: the claimed one.
          const changed = next.board.filter((c, i) => c !== before.board[i]);
          expect(changed).toEqual([actor]);
          // Roster and game identity are preserved.
          expect(next.players).toEqual(before.players);
          expect(next.game).toBe(TIC_TAC_TOE);
        } else {
          // Invalid move → Err(INVALID_MOVE) and input unchanged (Req 6.11).
          expect(isErr(result)).toBe(true);
          if (isErr(result)) {
            expect(result.error.code).toBe(ERROR_CODES.INVALID_MOVE);
          }
          expect(state).toStrictEqual(before);
        }
      }),
    );
  });

  it('is deterministic: the same move on the same state yields identical next state', () => {
    fc.assert(
      fc.property(stateArb, actorArb, moveArb, (state, actor, move) => {
        const a = applyMove(state as unknown as GameState, actor, move as unknown as Move);
        const b = applyMove(state as unknown as GameState, actor, move as unknown as Move);

        expect(isOk(a)).toBe(isOk(b));
        if (isOk(a) && isOk(b)) {
          // Identical authoritative state for both partners (Req 6.4).
          expect(a.value).toStrictEqual(b.value);
        }
      }),
    );
  });
});
