/* global URL, process, console */

import { createServer } from 'node:http';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { dirname, extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { planWorkspaceCatalogPublication } from './catalog-update.mjs';

const root = fileURLToPath(new URL('./public/', import.meta.url));
const appRoot = dirname(root);
const repositoryRoot = normalize(join(appRoot, '../..'));
const publishedLevelsFile = join(
  repositoryRoot,
  'packages/core/src/domain/elemental-published-levels.ts',
);
const archiveDirectory = join(appRoot, 'archived-levels');
const reloadTokenFile = join(
  repositoryRoot,
  'apps/game-server/src/platformer/level-reload-token.ts',
);
const runFile = promisify(execFile);
const port = Number(process.env.PORT ?? 4179);
const types = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.mjs': 'text/javascript',
  '.svg': 'image/svg+xml',
};
let catalogMutationQueue = Promise.resolve();

function serializeCatalogMutation(task) {
  const result = catalogMutationQueue.then(task);
  catalogMutationQueue = result.then(
    () => undefined,
    () => undefined,
  );
  return result;
}

async function loadBuiltLevels() {
  const moduleUrl = new URL(
    '../../packages/core/dist/domain/elemental-platformer.js',
    import.meta.url,
  );
  // A fresh process avoids Node's cache for the catalog's imported generated module.
  const { stdout } = await runFile(
    process.execPath,
    [
      '--input-type=module',
      '-e',
      `import { ELEMENTAL_AUTHORED_LEVELS } from ${JSON.stringify(moduleUrl.href)}; process.stdout.write(JSON.stringify(ELEMENTAL_AUTHORED_LEVELS));`,
    ],
    { cwd: repositoryRoot },
  );
  return JSON.parse(stdout).map((level, index) => ({
    number: index + 1,
    level,
  }));
}

async function archiveLevel(targetNumber, level, reason = 'update') {
  await mkdir(archiveDirectory, { recursive: true });
  const archivedAt = new Date().toISOString();
  const timestamp = archivedAt.replaceAll(':', '-').replaceAll('.', '-');
  const safeId = String(level.id ?? `level-${targetNumber}`).replace(/[^a-zA-Z0-9_-]+/g, '-');
  const filename = `${timestamp}-slot-${targetNumber}-${safeId}.json`;
  const archive = { archivedAt, targetNumber, reason, level };
  await writeFile(join(archiveDirectory, filename), `${JSON.stringify(archive, null, 2)}\n`);
  return filename;
}

async function archivedLevels() {
  await mkdir(archiveDirectory, { recursive: true });
  const filenames = (await readdir(archiveDirectory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()
    .reverse();
  return Promise.all(
    filenames.map(async (filename) => ({
      filename,
      ...JSON.parse(await readFile(join(archiveDirectory, filename), 'utf8')),
    })),
  );
}

function assertTrustedMutationRequest(request) {
  const origin = request.headers.origin;
  const allowedOrigins = new Set([`http://127.0.0.1:${port}`, `http://localhost:${port}`]);
  if (origin && !allowedOrigins.has(origin)) throw new Error('Untrusted mutation origin');
  if (request.headers['sec-fetch-site'] === 'cross-site')
    throw new Error('Cross-site mutation denied');
}

function assertCrystalRequirements(level) {
  if (!Array.isArray(level.crystals) || level.crystals.length > 16)
    throw new Error('A level can contain at most 16 crystals');
  for (const role of ['ember', 'tide']) {
    const available = level.crystals.filter((crystal) => crystal.role === role).length;
    const required = level.requiredCrystals?.[role];
    if (!Number.isInteger(required) || required < 0 || required > available)
      throw new Error(
        `${role} gate needs a whole-number crystal requirement from 0 to ${available}`,
      );
  }
}

async function installLiveCatalog(levels) {
  if (!levels.length || new Set(levels.map((level) => level.id)).size !== levels.length)
    throw new Error('Live catalog needs unique level IDs');
  const installed = levels.map((level, index) => {
    assertCrystalRequirements(level);
    const numbered = { ...level, number: index + 1, chapter: `Level ${index + 1}` };
    delete numbered.order;
    return numbered;
  });
  const previousSource = await readFile(publishedLevelsFile, 'utf8');
  await writeFile(
    publishedLevelsFile,
    `import type { ElementalLevel } from './elemental-platformer.js';\n\n// Generated by Level Forge. Do not edit by hand.\nexport const ELEMENTAL_PUBLISHED_LEVELS: readonly ElementalLevel[] = ${JSON.stringify(installed, null, 2)};\n`,
  );
  try {
    await runFile('npm', ['exec', 'prettier', '--', '--write', publishedLevelsFile], {
      cwd: repositoryRoot,
    });
    await runFile('npm', ['run', 'build', '--workspace', '@ldr/core'], {
      cwd: repositoryRoot,
    });
  } catch (error) {
    await writeFile(publishedLevelsFile, previousSource);
    await runFile('npm', ['run', 'build', '--workspace', '@ldr/core'], {
      cwd: repositoryRoot,
    });
    throw error;
  }
  await writeFile(
    reloadTokenFile,
    `// Generated by Level Forge to restart the development game server.\nexport const LEVEL_RELOAD_TOKEN = ${JSON.stringify(new Date().toISOString())};\n`,
  );
  return installed;
}

createServer(async (request, response) => {
  try {
    if (request.url === '/api/push-catalog' && request.method === 'POST') {
      assertTrustedMutationRequest(request);
      let source = '';
      for await (const chunk of request) {
        source += chunk;
        if (source.length > 5_000_000) throw new Error('Catalog payload is too large');
      }
      const payload = JSON.parse(source);
      const workspaceLevels = payload.levels;
      if (
        !Array.isArray(workspaceLevels) ||
        workspaceLevels.length > 64 ||
        workspaceLevels.some(
          (level) =>
            !level?.id || !Array.isArray(level.platforms) || !Array.isArray(level.crystals),
        )
      )
        throw new Error('Provide a complete workspace level tree (up to 64 levels)');
      for (const level of workspaceLevels) assertCrystalRequirements(level);
      const result = await serializeCatalogMutation(async () => {
        const currentLevels = (await loadBuiltLevels()).map((entry) => entry.level);
        const plan = planWorkspaceCatalogPublication(
          currentLevels,
          workspaceLevels,
          payload.activeIndex,
        );
        for (const level of currentLevels) await archiveLevel(level.number, level, 'publish');
        const installed = await installLiveCatalog(plan.levels);
        return {
          ok: true,
          activeNumber: plan.activeNumber,
          preservedLiveCount: plan.preservedLiveCount,
          levels: installed,
        };
      });
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify(result));
      return;
    }
    if (request.url === '/api/push-level' && request.method === 'POST')
      throw new Error('Refresh Level Forge; publishing now updates the whole level tree');
    if (request.url === '/api/archived-levels' && request.method === 'GET') {
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify(await archivedLevels()));
      return;
    }
    if (request.url === '/api/archived-levels' && request.method === 'POST') {
      assertTrustedMutationRequest(request);
      let source = '';
      for await (const chunk of request) {
        source += chunk;
        if (source.length > 1_000_000) throw new Error('Level payload is too large');
      }
      const level = JSON.parse(source)?.level;
      if (!level?.id || !Number.isInteger(Number(level.number)))
        throw new Error('A numbered level is required for archiving');
      const archivedAs = await archiveLevel(Number(level.number), level, 'manual');
      response.writeHead(201, { 'content-type': 'application/json' });
      response.end(JSON.stringify({ ok: true, archivedAs }));
      return;
    }
    if (request.url === '/api/reorder-levels' && request.method === 'POST') {
      assertTrustedMutationRequest(request);
      let source = '';
      for await (const chunk of request) {
        source += chunk;
        if (source.length > 16_384) throw new Error('Catalog reorder payload is too large');
      }
      const orderedIds = JSON.parse(source)?.orderedIds;
      const installed = await serializeCatalogMutation(async () => {
        const currentLevels = (await loadBuiltLevels()).map((entry) => entry.level);
        const currentIds = currentLevels.map((level) => level.id);
        if (
          !Array.isArray(orderedIds) ||
          orderedIds.length !== currentIds.length ||
          new Set(orderedIds).size !== currentIds.length ||
          orderedIds.some((id) => !currentIds.includes(id))
        )
          throw new Error('Live order must be an exact permutation of the current catalog');
        for (const level of currentLevels) await archiveLevel(level.number, level, 'reorder');
        const byId = new Map(currentLevels.map((level) => [level.id, level]));
        return installLiveCatalog(orderedIds.map((id) => byId.get(id)));
      });
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify({ ok: true, levels: installed }));
      return;
    }
    if (request.url === '/docs') {
      const body = await readFile(
        new URL('../../docs/ember-tide-level-authoring-rules.md', import.meta.url),
      );
      response.writeHead(200, { 'content-type': 'text/plain; charset=utf-8' });
      response.end(body);
      return;
    }
    if (request.url === '/api/levels') {
      const currentLevels = await serializeCatalogMutation(loadBuiltLevels);
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify(currentLevels.map((entry) => entry.level)));
      return;
    }
    const requested =
      request.url === '/' ? 'index.html' : (request.url?.split('?')[0]?.slice(1) ?? '');
    const path = normalize(join(root, requested));
    if (!path.startsWith(root)) throw new Error('Invalid path');
    const body = await readFile(path);
    response.writeHead(200, {
      'content-type': `${types[extname(path)] ?? 'application/octet-stream'}; charset=utf-8`,
    });
    response.end(body);
  } catch (error) {
    if (
      request.url === '/api/push-level' ||
      request.url === '/api/push-catalog' ||
      request.url === '/api/archived-levels' ||
      request.url === '/api/reorder-levels'
    ) {
      response.writeHead(400, { 'content-type': 'application/json' });
      response.end(
        JSON.stringify({ error: error instanceof Error ? error.message : 'Level update failed' }),
      );
      return;
    }
    response.writeHead(404);
    response.end('Not found');
  }
}).listen(port, '127.0.0.1', () => {
  console.log(`Ember & Tide Level Builder: http://localhost:${port}`);
});
