/* global URL, process, console */

import { createServer } from 'node:http';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { dirname, extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('./public/', import.meta.url));
const appRoot = dirname(root);
const repositoryRoot = normalize(join(appRoot, '../..'));
const coreLevelFile = join(repositoryRoot, 'packages/core/src/domain/elemental-platformer.ts');
const archiveDirectory = join(appRoot, 'archived-levels');
const reloadTokenFile = join(
  repositoryRoot,
  'apps/game-server/src/platformer/level-reload-token.ts',
);
const runFile = promisify(execFile);
const port = Number(process.env.PORT ?? 4179);
const types = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.mjs': 'text/javascript',
  '.svg': 'image/svg+xml',
};

const liveSlots = {
  1: { constant: 'ELEMENTAL_SPLITROOT_TEMPLE_LEVEL', exportName: 'ELEMENTAL_GROVE_LEVEL' },
  2: { constant: 'ELEMENTAL_FOUNDRY_LEVEL', exportName: 'ELEMENTAL_FOUNDRY_LEVEL' },
  3: { constant: 'ELEMENTAL_DUNGEON_LEVEL', exportName: 'ELEMENTAL_DUNGEON_LEVEL' },
};

async function loadBuiltLevels() {
  const moduleUrl = new URL(
    '../../packages/core/dist/domain/elemental-platformer.js',
    import.meta.url,
  );
  moduleUrl.searchParams.set('updated', String(Date.now()));
  const built = await import(moduleUrl.href);
  return Object.entries(liveSlots).map(([number, slot]) => ({
    number: Number(number),
    level: built[slot.exportName],
  }));
}

async function archiveLevel(targetNumber, level, reason = 'overwrite') {
  await mkdir(archiveDirectory, { recursive: true });
  const archivedAt = new Date().toISOString();
  const timestamp = archivedAt.replaceAll(':', '-').replaceAll('.', '-');
  const safeId = String(level.id ?? `level-${targetNumber}`).replace(/[^a-zA-Z0-9_-]+/g, '-');
  const filename = `${timestamp}-slot-${targetNumber}-${safeId}.json`;
  const archive = { archivedAt, targetNumber, reason, level };
  await writeFile(join(archiveDirectory, filename), `${JSON.stringify(archive, null, 2)}\n`);
  return filename;
}

async function archivedLevels() {
  await mkdir(archiveDirectory, { recursive: true });
  const filenames = (await readdir(archiveDirectory))
    .filter((filename) => filename.endsWith('.json'))
    .sort()
    .reverse();
  return Promise.all(
    filenames.map(async (filename) => ({
      filename,
      ...JSON.parse(await readFile(join(archiveDirectory, filename), 'utf8')),
    })),
  );
}

function assertTrustedMutationRequest(request) {
  const origin = request.headers.origin;
  const allowedOrigins = new Set([`http://127.0.0.1:${port}`, `http://localhost:${port}`]);
  if (origin && !allowedOrigins.has(origin)) throw new Error('Untrusted mutation origin');
  if (request.headers['sec-fetch-site'] === 'cross-site')
    throw new Error('Cross-site mutation denied');
}

async function installLiveCatalog(levels) {
  let source = await readFile(coreLevelFile, 'utf8');
  Object.entries(liveSlots).forEach(([number, slot], index) => {
    const level = {
      ...levels[index],
      number: Number(number),
      chapter: `Level ${number}`,
    };
    delete level.order;
    const matcher = new RegExp(
      `export const ${slot.constant} = \\{[\\s\\S]*?\\n\\} as const satisfies ElementalLevel;`,
    );
    if (!matcher.test(source)) throw new Error(`Could not locate ${slot.constant} in shared core`);
    source = source.replace(
      matcher,
      `export const ${slot.constant} = ${JSON.stringify(level, null, 2)} as const satisfies ElementalLevel;`,
    );
  });
  await writeFile(coreLevelFile, source);
  await runFile('npm', ['exec', 'prettier', '--', '--write', coreLevelFile], {
    cwd: repositoryRoot,
  });
  await runFile('npm', ['run', 'build', '--workspace', '@ldr/core'], {
    cwd: repositoryRoot,
  });
  await writeFile(
    reloadTokenFile,
    `// Generated by Level Forge to restart the development game server.\nexport const LEVEL_RELOAD_TOKEN = ${JSON.stringify(new Date().toISOString())};\n`,
  );
  return levels.map((level, index) => ({
    ...level,
    number: index + 1,
    chapter: `Level ${index + 1}`,
  }));
}

createServer(async (request, response) => {
  try {
    if (request.url === '/api/push-level' && request.method === 'POST') {
      assertTrustedMutationRequest(request);
      let source = '';
      for await (const chunk of request) {
        source += chunk;
        if (source.length > 1_000_000) throw new Error('Level payload is too large');
      }
      const payload = JSON.parse(source);
      const targetNumber = Number(payload.targetNumber);
      const slot = liveSlots[targetNumber];
      const level = payload.level;
      const constant = slot?.constant;
      if (
        !constant ||
        !level.id ||
        !Array.isArray(level.platforms) ||
        !Array.isArray(level.crystals)
      )
        throw new Error('Choose an existing live level and provide a complete authored level');
      const currentLevels = await loadBuiltLevels();
      const currentTarget = currentLevels.find((entry) => entry.number === targetNumber)?.level;
      if (!currentTarget) throw new Error(`Live Level ${targetNumber} could not be loaded`);
      const archivedAs = await archiveLevel(targetNumber, currentTarget);
      const installedLevel = {
        ...level,
        number: targetNumber,
        chapter: `Level ${targetNumber}`,
      };
      const current = await readFile(coreLevelFile, 'utf8');
      const matcher = new RegExp(
        `export const ${constant} = \\{[\\s\\S]*?\\n\\} as const satisfies ElementalLevel;`,
      );
      if (!matcher.test(current)) throw new Error(`Could not locate ${constant} in shared core`);
      const replacement = `export const ${constant} = ${JSON.stringify(installedLevel, null, 2)} as const satisfies ElementalLevel;`;
      await writeFile(coreLevelFile, current.replace(matcher, replacement));
      await runFile('npm', ['exec', 'prettier', '--', '--write', coreLevelFile], {
        cwd: repositoryRoot,
      });
      await runFile('npm', ['run', 'build', '--workspace', '@ldr/core'], {
        cwd: repositoryRoot,
      });
      await writeFile(
        reloadTokenFile,
        `// Generated by Level Forge to restart the development game server.\nexport const LEVEL_RELOAD_TOKEN = ${JSON.stringify(new Date().toISOString())};\n`,
      );
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify({ ok: true, level: targetNumber, archivedAs, installedLevel }));
      return;
    }
    if (request.url === '/api/archived-levels' && request.method === 'GET') {
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify(await archivedLevels()));
      return;
    }
    if (request.url === '/api/archived-levels' && request.method === 'POST') {
      assertTrustedMutationRequest(request);
      let source = '';
      for await (const chunk of request) {
        source += chunk;
        if (source.length > 1_000_000) throw new Error('Level payload is too large');
      }
      const level = JSON.parse(source)?.level;
      if (!level?.id || !Number.isInteger(Number(level.number)))
        throw new Error('A numbered level is required for archiving');
      const archivedAs = await archiveLevel(Number(level.number), level, 'manual');
      response.writeHead(201, { 'content-type': 'application/json' });
      response.end(JSON.stringify({ ok: true, archivedAs }));
      return;
    }
    if (request.url === '/api/reorder-levels' && request.method === 'POST') {
      assertTrustedMutationRequest(request);
      let source = '';
      for await (const chunk of request) {
        source += chunk;
        if (source.length > 16_384) throw new Error('Catalog reorder payload is too large');
      }
      const orderedIds = JSON.parse(source)?.orderedIds;
      const currentLevels = (await loadBuiltLevels()).map((entry) => entry.level);
      const currentIds = currentLevels.map((level) => level.id);
      if (
        !Array.isArray(orderedIds) ||
        orderedIds.length !== currentIds.length ||
        new Set(orderedIds).size !== currentIds.length ||
        orderedIds.some((id) => !currentIds.includes(id))
      )
        throw new Error('Live order must be an exact permutation of the current catalog');
      for (const level of currentLevels) await archiveLevel(level.number, level, 'reorder');
      const byId = new Map(currentLevels.map((level) => [level.id, level]));
      const reordered = orderedIds.map((id) => byId.get(id));
      const installed = await installLiveCatalog(reordered);
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify({ ok: true, levels: installed }));
      return;
    }
    if (request.url === '/docs') {
      const body = await readFile(
        new URL('../../docs/ember-tide-level-authoring-rules.md', import.meta.url),
      );
      response.writeHead(200, { 'content-type': 'text/plain; charset=utf-8' });
      response.end(body);
      return;
    }
    if (request.url === '/api/levels') {
      response.writeHead(200, { 'content-type': 'application/json' });
      response.end(JSON.stringify((await loadBuiltLevels()).map((entry) => entry.level)));
      return;
    }
    const requested =
      request.url === '/' ? 'index.html' : (request.url?.split('?')[0]?.slice(1) ?? '');
    const path = normalize(join(root, requested));
    if (!path.startsWith(root)) throw new Error('Invalid path');
    const body = await readFile(path);
    response.writeHead(200, {
      'content-type': `${types[extname(path)] ?? 'application/octet-stream'}; charset=utf-8`,
    });
    response.end(body);
  } catch (error) {
    if (
      request.url === '/api/push-level' ||
      request.url === '/api/archived-levels' ||
      request.url === '/api/reorder-levels'
    ) {
      response.writeHead(400, { 'content-type': 'application/json' });
      response.end(
        JSON.stringify({ error: error instanceof Error ? error.message : 'Level update failed' }),
      );
      return;
    }
    response.writeHead(404);
    response.end('Not found');
  }
}).listen(port, '127.0.0.1', () => {
  console.log(`Ember & Tide Level Builder: http://localhost:${port}`);
});
